facebook:
  client:
    clientId: 659596220915072
    clientSecret: 76b5d3a74f07039cf0574525ac4bda83

logging:
  level:
    org.springframework: ERROR
    com.wetjens.powergrid.server: DEBUG

spring:
  thymeleaf:
    cache: false