version: '2'
services:
  web:
    build: .
    ports:
      - '8080:8080'
    environment:
      SPRING_DATA_MONGODB_HOST: db
      SPRING_PROFILES_ACTIVE: development
      SPRING_SOCIAL_FACEBOOK_APP_ID: 659596220915072
      SPRING_SOCIAL_FACEBOOK_APP_SECRET: 76b5d3a74f07039cf0574525ac4bda83
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - '27017:27017'
