spring:
  social:
    facebook:
      app-id: changeit
      app-secret: changeit

security:
  oauth2:
    client:
      client-id: powerline
      client-secret: powerlinesecret
      scope: basic
      auto-approve-scopes: basic
      authorized-grant-types: authorization_code, password, refresh_token
      access-token-validity-seconds: 600
      refresh-token-validity-seconds: 2592000
