spring:
  social:
    facebook:
      appId: appId
      appSecret: appSecret

security:
  oauth2:
    client:
      clientId: powerline
      clientSecret: powerlinesecret
      auto-approve-scopes: '.*'